import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import {
  LUCIDE_ICONS,
  LucideIconProvider,
  LayoutDashboard,
  Car,
  Users,
  UserCog,
  Key,
  ClipboardCheck,
  ShieldAlert,
  Plus,
  Pencil,
  Check,
  X,
  Search,
  Bell,
  ScanLine,
  Settings,
  LogOut,
  LogIn,
  ChevronsUpDown,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  Download,
  AlertTriangle,
  ArrowLeft,
  Clock,
  User,
  ImagePlus,
  ImageOff,
  Calendar,
  CircleCheck,
  Mail,
  MessageSquare,
  ShieldCheck,
  UserX,
  Wallet,
  Building2,
  Power,
  PowerOff,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/auth/interceptors/auth.interceptor';
import { errorInterceptor } from './core/auth/interceptors/error.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(
      withFetch(),
      withInterceptors([authInterceptor, errorInterceptor]),
    ),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        LayoutDashboard,
        Car,
        Users,
        UserCog,
        Key,
        ClipboardCheck,
        ShieldAlert,
        Plus,
        Pencil,
        Check,
        X,
        Search,
        Bell,
        ScanLine,
        Settings,
        LogOut,
        LogIn,
        ChevronsUpDown,
        ChevronLeft,
        ChevronRight,
        Sparkles,
        Download,
        AlertTriangle,
        ArrowLeft,
        Clock,
        User,
        ImagePlus,
        ImageOff,
        Calendar,
        CheckCircle: CircleCheck,
        Mail,
        MessageSquare,
        ShieldCheck,
        UserX,
        Wallet,
        Building2,
        Power,
        PowerOff,
      }),
    },
  ],
};
