export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
  },
  VEHICLES: {
    BASE: '/vehicles',
    BY_ID: (id: string) => `/vehicles/${id}`,
    IMAGES: (vehicleId: string) => `/vehicles/${vehicleId}/images`,
    IMAGE: (vehicleId: string, imageId: string) => `/vehicles/${vehicleId}/images/${imageId}`,
    SET_PRIMARY: (vehicleId: string, imageId: string) => `/vehicles/${vehicleId}/images/${imageId}/primary`,
  },
  CLIENTS: {
    BASE: '/clients',
    BY_ID: (id: string) => `/clients/${id}`,
    DETAILS: (id: string) => `/clients/${id}/details`,
  },
  EMPLOYEES: {
    BASE: '/employees',
    BY_ID: (id: string) => `/employees/${id}`,
    LOGIN_ACCESS: (id: string) => `/employees/${id}/login-account`,
    PERMISSIONS: (id: string) => `/employees/${id}/permissions`,
    STATS: (id: string) => `/employees/${id}/stats`,
    RECENT_INSPECTIONS: (id: string) => `/employees/${id}/recent-inspections`,
  },
  BRANCHES: {
    BASE: '/branches',
    BY_ID: (id: string) => `/branches/${id}`,
    ACTIVATE: (id: string) => `/branches/${id}/activate`,
    DEACTIVATE: (id: string) => `/branches/${id}/deactivate`,
  },
  RENTALS: {
    BASE: '/rentals',
    BY_ID: (id: string) => `/rentals/${id}`,
    CHANGE_STATUS: (id: string) => `/rentals/${id}/status`,
  },
  INSPECTIONS: {
    BASE: '/inspections',
    BY_ID: (id: string) => `/inspections/${id}`,
    PHOTOS: (inspectionId: string) => `/inspections/${inspectionId}/photos`,
    COMPLETE: (inspectionId: string) => `/inspections/${inspectionId}/complete`,
  },
  DAMAGE_REPORTS: {
    BASE: '/damage-reports',
    BY_ID: (id: string) => `/damage-reports/${id}`,
    ANALYZE: (reportId: string) => `/damage-reports/${reportId}/analyze`,
  },
  PROFILE: {
    BASE: '/profile',
    PASSWORD: '/profile/password',
    IMAGE: '/profile/image',
  },
  BILLING: {
    ACCOUNT: '/billing/account',
    USAGE: '/billing/usage',
  },
  SERVICE_BOOK: {
    RECORDS: '/service-book/records',
    RECORD_BY_ID: (id: string) => `/service-book/records/${id}`,
    REMINDERS: '/service-book/reminders',
    REMINDERS_BY_VEHICLE: (vehicleId: string) => `/service-book/reminders/by-vehicle/${vehicleId}`,
    REMINDERS_UPCOMING: '/service-book/reminders/upcoming',
    REMINDER_BY_ID: (id: string) => `/service-book/reminders/${id}`,
    REMINDER_DISMISS: (id: string) => `/service-book/reminders/${id}/dismiss`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/${id}/mark-read`,
    MARK_ALL_READ: '/notifications/mark-all-read',
  },
  PLATFORM: {
    TENANTS: '/platform/tenants',
    TENANT_BY_ID: (id: string) => `/platform/tenants/${id}`,
    TOP_UP: (id: string) => `/platform/tenants/${id}/topup`,
    MONTHLY_CAP: (id: string) => `/platform/tenants/${id}/monthly-cap`,
    LOW_BALANCE: (id: string) => `/platform/tenants/${id}/low-balance-threshold`,
    ASSIGN_PLAN: (id: string) => `/platform/tenants/${id}/pricing-plan`,
    SUSPEND: (id: string) => `/platform/tenants/${id}/suspend`,
    REACTIVATE: (id: string) => `/platform/tenants/${id}/reactivate`,
    DEACTIVATE: (id: string) => `/platform/tenants/${id}/deactivate`,
  },
} as const;
